### ISSUE TITLE
Error created by faulty project ID

### ISSUE THREAD

**Issue by guypursey** [guypursey/hithercontent#3]
If the project ID requested of `getProjectBranch` is not known to GatherContent, an error is thrown. If using on Heroku, this leads to an application crash. There needs to be a more graceful way for the function to fail.

This may also be true for item IDs and true of other HitherContent methods. More testing required.

**Comment by guypursey** [comment]
An example of some of what this error looks like:

```
undefined:1
Invalid credentials.
^

SyntaxError: Unexpected token I
    at Object.parse (native)

```

**Comment by guypursey** [comment]
Perhaps a separate issue but I have also found this error through testing:

```
\index.js:129
                        .filter(i => i.parent_id === root_id);
                        ^

TypeError: Cannot read property 'filter' of undefined
    at async.each (\node_modules\hithercontent\index.js:129:25)
    at child_items (\node_modules\hithercontent\index.js:143:19)
```

Removed pathnames from code to anonymise/generalise.

**Comment by thiagodemellobueno** [comment]
I'm having the same issue reported on Oct 31 2016:
```
const auth = JSON.parse(fs.readFileSync("_auth.json", { "encoding": "utf8" }))
const options = {
  project: {
    id: 'xxxxxxx' // anonymized for post
  }
}

… // later on

module.exports = function (opts) {
  hithercontent.init(auth)
  hithercontent.getProjectBranchWithFileInfo(options.project.id, function(a) {
      processHitherContentData(a, done)
    })
  }
}
```
Tracing out variables in hithercontent's index js, tells me that inside ```getProjectBranchWithFileInfo``` in the callback for 
```getJSONfromAPI```
```project_data``` is```{}```.

Any help would be appreciated!
